version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins
    build:
      context: jenkins
    ports:
      - "8080:8080"
      - "5000:5000"

    networks:
      - net
networks:
  net: